### ISSUE TITLE
ubuntu16 is not supported.

### ISSUE THREAD

**Issue by karlhiramoto** [aerospike/aerospike-client-nodejs#118]
It would be nice if any linux distro was supported  Arch, gentoo, or any other distro. 

```

karl@ubuntu16-server:/tmp/test$ npm install aerospike

> aerospike@2.0.0 install /tmp/test/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/tmp/test/node_modules/aerospike/build'
  TOUCH binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
error: ubuntu16 is not supported.
aerospike-client-c.target.mk:16: recipe for target 'binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate' failed
make: *** [binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate] Error 1
rm binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
make: Leaving directory '/tmp/test/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/test/node_modules/aerospike
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "aerospike"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! aerospike@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerospike@2.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aerospike
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/test/npm-debug.log

```

**Comment by jhecking** [comment]
> It would be nice if any linux distro was supported Arch, gentoo, or any other distro.

Agree. It's been on my todo list to rework the install script for the C client library for some time. I just haven't gotten around to it yet.

For now @NawarA already added support for Ubuntu 16.04 in PR #123.

**Comment by guidoocean** [comment]
I have literally same error. And I do everything to fix this. But looks it is imposimbru.

**Comment by jhecking** [comment]
You have the same error "ubuntu16 is not supported"?!

**Comment by guidoocean** [comment]
Yes. I'm try to install a 1.0.57 version according to my package.json file. Is it possible to install it? The latest version setups correctly.

**Comment by jhecking** [comment]
You can try your luck with [v1.0.58](https://github.com/aerospike/aerospike-client-nodejs/releases/tag/1.0.58), which is the last release on the v1 branch and which added support for Ubuntu 16. But I would strongly recommend that you upgrade to the v3 client as soon as possible.

**Comment by guidoocean** [comment]
Problem solved with v3. Sorry for necrothread. )
