### ISSUE TITLE
AerospikeError: AEROSPIKE_ERR_REQUEST_INVALID on map example

### ISSUE THREAD

**Issue by kinghadi** [aerospike/aerospike-client-nodejs#134]
**Problem**
I just copied and pasted the code for map operations to test it but it crashed with the `AEROSPIKE_ERR_REQUEST_INVALID`. 

_P.S: I'm using `aerospike-nodejs-lib v2.1.1` and `nodeJS v6`._

**Code**
Copied from [this link](http://www.aerospike.com/apidocs/nodejs/module-aerospike_maps.html):
``` javascript
const Aerospike = require('aerospike')
const maps = Aerospike.maps
const key = new Aerospike.Key('test', 'demo', 'key1')

var keyOrderedPolicy = { order: maps.order.KEY_ORDERED }
var createOnlyPolicy = { writeMode: maps.writeMode.CREATE_ONLY }
var ops = [
  maps.put('map', 'e', 5, keyOrderedPolicy),                    // => { map: { e: 5 } }
  maps.putItems('map', { d: 4, b: 2, c: 3 }),                   // => { map: { b: 2, c: 3, d: 4, e: 5 } }
  maps.putItems('map', { c: 99, a: 1 }, createOnlyPolicy),      // => { map: { a: 1, b: 2, c: 3, d: 4, e: 5 } }
  maps.removeByValue('map', 3),                                 // => { map: { a: 1, b: 2, d: 4, e: 5 } }
  maps.removeByIndexRange('map', -2, 2, maps.returnType.KEY)    // => { map: { a: 1, b: 2 } }
]

Aerospike.connect((error, client) => {
  if (error) throw error
  client.operate(key, ops, (error, result) => {
    if (error) throw error
    console.log(result)                                         // => { map: ['d', 'e'] }
    client.get(key, (error, record) => {
      if (error) throw error
      console.log(record)                                       // => { map: { a: 1, b: 2 } }
      client.close()
    })
  })
})
```

**Error**
```
if (error) throw error
               ^
AerospikeError: AEROSPIKE_ERR_REQUEST_INVALID
    at Function.AerospikeError.fromASError ( ./node_modules/aerospike/lib/aerospike_error.js:113:10)
    at Client.DefaultCallbackHandler [as callbackHandler] (./node_modules/aerospike/lib/client.js:71:72)
    at operateCb (./node_modules/aerospike/lib/client.js:1059:10)
```

**Comment by jhecking** [comment]
What version of the Aerospike server are you using? Sorted Map operations require the latest server [version 3.8.4](http://www.aerospike.com/download/server/notes.html#3.8.4). Please note that this feature is considered a developer preview at this point.

**Comment by kinghadi** [comment]
I'm using `aerospike v3.8.1`. when I want to run the following code, it also fails with the same error:
**Code**

``` javascript
const Aerospike = require('aerospike')
const maps = Aerospike.maps
const key = new Aerospike.Key('test', 'demo', 'key1')

var ops = [
  maps.put('map', 'e', 5)                    // => { map: { e: 5 } }
]

Aerospike.connect((error, client) => {
  if (error) throw error
  client.operate(key, ops, (error, result) => {
    if (error) throw error
    console.log(result)                                         // => { map: ['d', 'e'] }
    client.get(key, (error, record) => {
      if (error) throw error
      console.log(record)                                       // => { map: { a: 1, b: 2 } }
      client.close()
    })
  })
})
```

**Comment by jhecking** [comment]
You cannot use the `Aerospike.maps` module unless you are running AS 3.8.4. With earlier versions of AS you will need to fetch the entire map from the server, perform any desired operations client side, and then write the entire map back to the server.

**Comment by kinghadi** [comment]
thanks, I upgraded to version 3.8.4 and it worked!
