### ISSUE TITLE
Docker + Alpine = Can't build!

### ISSUE THREAD

**Issue by srfrnk** [aerospike/aerospike-client-nodejs#249]
Save this as Dockerfile:
```dockerfile
FROM node:9.3.0-alpine
RUN npm install aerospike
```

Then run:
```bash
docker build .
```

And get this:
```bash
.
.
.
> aerospike@3.2.0 install /app/node_modules/aerospike
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
.
.
.
```
However this works:
```dockerfile
FROM node:9.3.0
RUN npm install aerospike
```

Might be worth putting into the docs at least.

**Comment by jhecking** [comment]
This is a known limitation / feature (depending on who you ask!) of the `node:alpine` image. Does the solution suggested in [this issue](https://github.com/nodejs/docker-node/issues/384) help?

**Comment by srfrnk** [comment]
Sadly no:
```
> aerospike@3.2.0 install /app/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/app/node_modules/aerospike/build'
  TOUCH binding_gyp_aerospike_client_c_target_Installing_Aerospike_C_Client_dependency.intermediate
  ACTION binding_gyp_aerospike_client_c_target_Installing_Aerospike_C_Client_dependency binding_gyp_aerospike_client_c_target_Installing_Aerospike_C_Client_dependency.intermediate
/bin/sh: scripts/aerospike-client-c.sh: not found
make: *** [aerospike-client-c.target.mk:17: binding_gyp_aerospike_client_c_target_Installing_Aerospike_C_Client_dependency.intermediate] Error 127
rm binding_gyp_aerospike_client_c_target_Installing_Aerospike_C_Client_dependency.intermediate
make: Leaving directory '/app/node_modules/aerospike/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.0-36-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/aerospike
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by jhecking** [comment]
I am not sure why you are getting this error: "scripts/aerospike-client-c.sh: not found".

But in any case, for Alpine Linux we do not provide official releases for the Aerospike C client, which is required to build the Node.js client. So the C client needs to be compiled from source first. Here is a Dockerfile that does exactly that:

```
# Stage 1: Build Aerospike C client
FROM alpine:3.6 as c-builder
WORKDIR /src

ENV AS_C_VERSION 4.3.5

RUN apk update
RUN apk add --no-cache \
    build-base \
    bash linux-headers \
    libuv libuv-dev \
    openssl openssl-dev \
    lua5.1 lua5.1-dev

RUN wget https://artifacts.aerospike.com/aerospike-client-c/${AS_C_VERSION}/aerospike-client-c-src-${AS_C_VERSION}.zip \
    && unzip aerospike-client-c-src-${AS_C_VERSION}.zip \
    && mv aerospike-client-c-src-${AS_C_VERSION} aerospike-client-c \
    && cd aerospike-client-c \
    && make EVENT_LIB=libuv

# Stage 2: Build Aerospike Node.js client
FROM node:9-alpine as node-builder
WORKDIR /src

COPY --from=c-builder /src/aerospike-client-c/target/Linux-x86_64/include/ aerospike-client-c/include/
COPY --from=c-builder /src/aerospike-client-c/target/Linux-x86_64/lib/ aerospike-client-c/lib/

ENV AS_NODEJS_VERSION 3.2.0
ENV PREFIX=/src/aerospike-client-c/

RUN apk update
RUN apk add --no-cache \
      build-base bash python linux-headers zlib-dev
RUN npm install aerospike@${AS_NODEJS_VERSION}

# Stage 3: Aerospike Node.js Runtime
FROM node:9-alpine
WORKDIR /src
COPY --from=node-builder /src/node_modules/ node_modules/
```

**Comment by srfrnk** [comment]
That works @jhecking - great solution!
