### ISSUE TITLE
Error installing aerospike-client-nodejs

### ISSUE THREAD

**Issue by rajat19** [aerospike/aerospike-client-nodejs#276]
Tried using `npm install aerospike` for my project 
This generated
```
> aerospike@3.6.1 install /home/rajat/Desktop/paytm/market-promo-search/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/home/abc/Desktop/my_project/node_modules/aerospike/build'
  ACTION binding_gyp_aerospike_client_c_target_Installing_Aerospike_C_Client_dependency 
info: downloading 'https://artifacts.aerospike.com/aerospike-client-c/4.3.17/aerospike-client-c-libuv-4.3.17.ubuntu18.04.x86_64.tgz' to 'aerospike-client-c-libuv-4.3.17.ubuntu18.04.x86_64.tgz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   387  100   387    0     0    691      0 --:--:-- --:--:-- --:--:--   689
100 2053k  100 2053k    0     0   193k      0  0:00:10  0:00:10 --:--:--  340k
grep aerospike-client-c-libuv-4.3.17.ubuntu18.04.x86_64.tgz /home/rajat/Desktop/paytm/market-promo-search/node_modules/aerospike/aerospike-client-c.sha256
info: verifying checksum for 'aerospike-client-c-libuv-4.3.17.ubuntu18.04.x86_64.tgz': OK
info: extracting devel package from 'aerospike-client-c-libuv-4.3.17.ubuntu18.04.x86_64.tgz'
info: extracting files from 'aerospike-client-c-libuv-devel-4.3.17.ubuntu18.04.x86_64.deb'

CHECK
   [✓] /home/abc/Desktop/my_project/node_modules/aerospike/aerospike-client-c/package/usr/lib/libaerospike.a
   [✓] /home/abc/Desktop/my_project/node_modules/aerospike/aerospike-client-c/package/usr/include/aerospike/aerospike.h

  TOUCH Release/obj.target/aerospike-client-c.stamp
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
  CXX(target) Release/obj.target/aerospike/src/main/client.o
  CXX(target) Release/obj.target/aerospike/src/main/config.o
  CXX(target) Release/obj.target/aerospike/src/main/events.o
  CXX(target) Release/obj.target/aerospike/src/main/operations.o
  CXX(target) Release/obj.target/aerospike/src/main/policy.o
  CXX(target) Release/obj.target/aerospike/src/main/query.o
  CXX(target) Release/obj.target/aerospike/src/main/scan.o
  CXX(target) Release/obj.target/aerospike/src/main/predexp.o
  CXX(target) Release/obj.target/aerospike/src/main/async.o
  CXX(target) Release/obj.target/aerospike/src/main/command.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/apply_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/batch_exists.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/batch_get.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/batch_select.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/batch_read_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/exists_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/get_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/info.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/info_foreach.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/job_info.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/operate_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/put_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/query_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/query_apply.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/query_background.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/query_foreach.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/remove_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/scan_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/scan_background.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/select_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/truncate.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/index_create.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/index_remove.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/udf_register.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/udf_remove.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/predicates.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/maps.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/lists.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/index.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/policy_enum.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/status.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/scanPriority.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/job_status.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/udf_languages.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/ttl.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/config_enum.o
  CXX(target) Release/obj.target/aerospike/src/main/util/conversions.o
  CXX(target) Release/obj.target/aerospike/src/main/util/log.o
  SOLINK_MODULE(target) Release/obj.target/aerospike.node
/usr/bin/x86_64-linux-gnu-ld: cannot find -lz
collect2: error: ld returned 1 exit status
aerospike.target.mk:196: recipe for target 'Release/obj.target/aerospike.node' failed
make: *** [Release/obj.target/aerospike.node] Error 1
rm ebf8c619d512e7a1a724a0ecb06ec5eec50df7dc.intermediate
make: Leaving directory '/home/abc/Desktop/my_project/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-33-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/abc/Desktop/my_project/node_modules/aerospike
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aerospike@3.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerospike@3.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jhecking** [comment]
> /usr/bin/x86_64-linux-gnu-ld: cannot find -lz

You need to install the libz compression library first, before installing the client. Please check the [Prerequisites](https://github.com/aerospike/aerospike-client-nodejs#Prerequisites) section of the readme for details.

**Comment by rajat19** [comment]
`sudo apt-get install g++ libssl1.0.0 libssl-dev libz-dev`
fixed the issue (given in Prerequisites)
