### ISSUE TITLE
Docker alpine-10 with aerospike not working

### ISSUE THREAD

**Issue by vikasjindal100** [aerospike/aerospike-client-nodejs#299]
My docker file is - 

```FROM node:10-alpine

MAINTAINER me

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json ./

RUN apk add --no-cache python2 make gcc g++ git libtool autoconf automake linux-headers \
openssl-dev zlib-dev libuv-dev

RUN git clone https://github.com/aerospike/aerospike-client-c.git && \
  cd aerospike-client-c && \
  git checkout --detach 4.3.20 && \
  git submodule update --init && \
  make EVENT_LIB=libuv

RUN npm install

VOLUME ["./logs"]

COPY . .

EXPOSE 9008

CMD [ "npm", "start" ]
```

On docker build, getting error - 

```
make: *** [aerospike-client-c.target.mk:17: ebf8c619d512e7a1a724a0ecb06ec5eec50df7dc.intermediate] Error 1
rm ebf8c619d512e7a1a724a0ecb06ec5eec50df7dc.intermediate
make: Leaving directory '/usr/src/app/node_modules/aerospike/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.4.0-1077-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/aerospike
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aerospike@3.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aerospike@3.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by jhecking** [comment]
>   git checkout --detach 4.3.20

That's an old version of the C client. If you are building Node.js client v3.10.0, you will need C client version 3.6.1. You can lookup the required version in [aerospike-client-c.ini](https://github.com/aerospike/aerospike-client-nodejs/blob/v3.10.0/aerospike-client-c.ini).

**Comment by jindalvi** [comment]
Updated C client version to 4.6.1.

My current Dockerfile- 

```
FROM node:10-alpine

MAINTAINER me

# Create directory if not present
RUN mkdir -p /usr/src/app

# Sets work directory
WORKDIR /usr/src/app

# Copy package.json
COPY package.json ./

RUN apk add --no-cache python2 make gcc g++ git libtool autoconf automake linux-headers \
openssl-dev zlib-dev libuv-dev

RUN git clone https://github.com/aerospike/aerospike-client-c.git && \
  cd aerospike-client-c && \
  git checkout --detach 4.6.1 && \
  git submodule update --init && \
  make EVENT_LIB=libuv

# Installs dependencies
RUN npm install

# Volume mount
VOLUME ["./logs"]

# Copy working files
COPY . .

# Expose port
EXPOSE 9008

# Starts run command
CMD [ "npm", "start" ]

```

I am still getting the following error - 

```

> aerospike@3.10.0 install /usr/src/app/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/usr/src/app/node_modules/aerospike/build'
  TOUCH ebf8c619d512e7a1a724a0ecb06ec5eec50df7dc.intermediate
  ACTION binding_gyp_aerospike_client_c_target_Installing_Aerospike_C_Client_dependency ebf8c619d512e7a1a724a0ecb06ec5eec50df7dc.intermediate
rm ebf8c619d512e7a1a724a0ecb06ec5eec50df7dc.intermediate
make: Leaving directory '/usr/src/app/node_modules/aerospike/build'
error: Linux distribution not supported: 'alpine3.9.4'
make: *** [aerospike-client-c.target.mk:17: ebf8c619d512e7a1a724a0ecb06ec5eec50df7dc.intermediate] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.4.0-1077-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/aerospike
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aerospike@3.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aerospike@3.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-20T07_00_04_837Z-debug.log
```

**Comment by jhecking** [comment]
It looks like you are not setting the PREFIX environment variable to the C client target dir before you build the Node.js client. If the Node.js client build script can't find your custom C client build it will download a new copy of the C client.

See https://github.com/aerospike/aerospike-client-nodejs/blob/master/README.md#Custom-Search-Path

**Comment by jindalvi** [comment]
@jhecking I am not able to figure out exactly how should I set the PREFIX environment variable to the C client target dir. Can you please help me with that. It would be very helpful if you could edit my docker file with what changes need to be done.

**Comment by jhecking** [comment]
I've added an example Dockerfile that shows how to build the Node.js client on Alpine Linux here: [docker/Dockerfile.alpine](https://github.com/aerospike/aerospike-client-nodejs/blob/master/docker/Dockerfile.alpine).

**Comment by jindalvi** [comment]
Current Dockerfile is - 

```
# Stage 1: Build Aerospike C client
FROM alpine:3.9 as c-builder
WORKDIR /src

ENV AS_C_VERSION 4.6.3

RUN apk update
RUN apk add --no-cache \
    build-base \
    linux-headers \
    bash \
    libuv-dev \
    openssl-dev \
    lua5.1-dev \
    zlib-dev

RUN wget https://artifacts.aerospike.com/aerospike-client-c/${AS_C_VERSION}/aerospike-client-c-src-${AS_C_VERSION}.zip \
    && unzip aerospike-client-c-src-${AS_C_VERSION}.zip \
    && mv aerospike-client-c-src-${AS_C_VERSION} aerospike-client-c \
    && cd aerospike-client-c \
    && make EVENT_LIB=libuv

# Stage 2: Build Aerospike Node.js client
FROM node:9-alpine as node-builder
WORKDIR /src

COPY --from=c-builder /src/aerospike-client-c/target/Linux-x86_64/include/ aerospike-client-c/include/
COPY --from=c-builder /src/aerospike-client-c/target/Linux-x86_64/lib/ aerospike-client-c/lib/

ENV AS_NODEJS_VERSION 3.11.0
ENV PREFIX=/src/aerospike-client-c

RUN apk update
RUN apk add --no-cache \
      build-base \
      bash \
      python \
      linux-headers \
      zlib-dev \
      openssl-dev

RUN npm install aerospike@${AS_NODEJS_VERSION}

# Stage 3: Aerospike Node.js Runtime
FROM node:10-alpine

MAINTAINER Vikas Jindal  <vikas.j@turtlemint.com>

# Create directory if not present
RUN mkdir -p /src

# Sets work directory
WORKDIR /src

COPY --from=node-builder /src/node_modules/ node_modules/

# Copy package.json
COPY package.json ./

# Installs dependencies
RUN npm install

# Volume mount
VOLUME ["./logs"]

# Copy working files
COPY . .

# Expose port
EXPOSE 9008

# Starts run command
CMD [ "npm", "start" ]
```

Every time I remove all the images and then run build command for the first time. I get following error - 
```
Step 20/26 : COPY --from=node-builder /src/node_modules/ node_modules/
failed to mount sha256:955d9fb1e2e52cbb4d7f09406655b00ae2ce115ce5e20bab70b204513a8294d2: no such image: sha256:955d9fb1e2e52cbb4d7f09406655b00ae2ce115ce5e20bab70b204513a8294d2: No such image: sha256:955d9fb1e2e52cbb4d7f09406655b00ae2ce115ce5e20bab70b204513a8294d2
```

Then after this if I build it again. Then it builds successfully.

But after running the Docker run command (`docker run --name form-config -v /var/log/form-config:/src/logs --network="host" -p 9008:9008 -d form-config`) 
Docker logs give prints following error -
```
> form-config@0.0.0 start /src
> node server.js

Error: Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /src/node_modules/aerospike/build/Release/aerospike.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.wrappedLoad (/src/node_modules/newrelic/lib/shimmer.js:353:38)
    at Function._load (/src/node_modules/@sentry/node/dist/integrations/console.js:41:47)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (/src/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/src/node_modules/aerospike/lib/aerospike.js:19:31)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.wrappedLoad (/src/node_modules/newrelic/lib/shimmer.js:353:38)
    at Function._load (/src/node_modules/@sentry/node/dist/integrations/console.js:41:47)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/src/services/cacheService.js:1:81)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
New Relic for Node.js halted startup due to an error:
Error: Not starting without license key!
    at onNextTick (/src/node_modules/newrelic/lib/agent.js:153:16)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! form-config@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the form-config@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-23T08_53_31_375Z-debug.log
```

**Comment by jhecking** [comment]
> Error: Error loading shared library libssl.so.1.0.0

Please pull the latest version of the Dockerfile.alpine - I had added missing libssl runtime dependency in 42c18d1fb8459d142864ae501131f0c7fe7c93b9 shortly after my last comment here.

> failed to mount sha256:955d9fb1e2e52cbb4d7f09406655b00ae2ce115ce5e20bab70b204513a8294d2

I don't know what's causing this for you. I'm not able to replicate this problem.

**Comment by jindalvi** [comment]
Even after adding 
`RUN apk add --no-cache \
      zlib \
      openssl`

Still getting the same error - 
```
> form-config@0.0.0 start /src
> node server.js

Error: Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /src/node_modules/aerospike/build/Release/aerospike.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.wrappedLoad (/src/node_modules/newrelic/lib/shimmer.js:353:38)
    at Function._load (/src/node_modules/@sentry/node/dist/integrations/console.js:41:47)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (/src/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/src/node_modules/aerospike/lib/aerospike.js:19:31)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.wrappedLoad (/src/node_modules/newrelic/lib/shimmer.js:353:38)
    at Function._load (/src/node_modules/@sentry/node/dist/integrations/console.js:41:47)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/src/services/cacheService.js:1:81)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
New Relic for Node.js halted startup due to an error:
Error: Not starting without license key!
    at onNextTick (/src/node_modules/newrelic/lib/agent.js:153:16)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! form-config@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the form-config@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-23T10_32_38_013Z-debug.log
```

**Comment by jhecking** [comment]
Please post your full Dockerfile again.

This works for me:

* `Dockerfile`:
```
FROM node:10-alpine

# Create directory if not present
RUN mkdir -p /usr/src/app

# Sets work directory
WORKDIR /usr/src/app

RUN apk add --no-cache python2 make gcc g++ git libtool autoconf automake linux-headers \
openssl-dev zlib-dev libuv-dev

RUN git clone https://github.com/aerospike/aerospike-client-c.git && \
  cd aerospike-client-c && \
  git checkout --detach 4.6.3 && \
  git submodule update --init && \
  make EVENT_LIB=libuv

# Copy package.json
COPY package.json ./
COPY package-lock.json ./

# Installs dependencies
ENV PREFIX=/usr/src/app/aerospike-client-c/target/Linux-x86_64
RUN npm install

COPY test.js ./
ENV AEROSPIKE_HOSTS=192.168.1.59:32782
CMD node test
```

* `test.js`:
```
const as = require('aerospike')

const key = new as.Key('test', 'test', 'test')
as.connect().then(async client => {
  await client.put(key, { foo: 'bar' })
  const record = await client.get(key)
  console.log(record)
  client.close()
}).catch(error => {
  console.error(error)
  if (error.client) {
    error.client.close()
  }
})
```

* Build docker image:
```
$ docker build -t alpine-aerospike-issue-299 .
Sending build context to Docker daemon  30.31MB
Step 1/12 : FROM node:10-alpine
...
Successfully built c6cfee1612a0
Successfully tagged alpine-aerospike-issue-299:latest
```

* Run docker image:
```
$ docker run --rm alpine-aerospike-issue-299
May 27 2019 03:02:14 UTC: WARN (1) [as_pipe.c:202] [read_file] - Failed to open /proc/sys/net/core/wmem_max for reading
May 27 2019 03:02:14 UTC: WARN (1) [as_pipe.c:261] [get_buffer_size] - Failed to read /proc/sys/net/core/wmem_max; should be at least 5242880. Please verify.
May 27 2019 03:02:14 UTC: WARN (1) [as_pipe.c:202] [read_file] - Failed to open /proc/sys/net/core/rmem_max for reading
May 27 2019 03:02:14 UTC: WARN (1) [as_pipe.c:261] [get_buffer_size] - Failed to read /proc/sys/net/core/rmem_max; should be at least 15728640. Please verify.
Record {
  key:
   Key {
     ns: 'test',
     set: 'test',
     key: 'test',
     digest:
      <Buffer ee d5 e3 61 f7 0d c4 ab 19 71 3f c0 f6 87 74 62 8c a8 32 f6> },
  bins: { foo: 'bar' },
  ttl: -1,
  gen: 2 }
```

**Comment by jhecking** [comment]
I'm going to close this issue for now. Feel free to reopen, if you still have issues with the Aerospike client on Alpine 10.

**Comment by akanshgulati** [comment]
@jhecking I am also facing the same issue. Is the `Dockerfile.alpine` updated ? I have removed aerospike from package.json file and using the Dockerfile.alpine for manually compiling it.

**Comment by akanshgulati** [comment]
@jhecking Also, I can access `https://www.aerospike.com/artifacts/aerospike-client-c/4.6.9/` version too but the https://github.com/aerospike/aerospike-client-nodejs/blob/d29cb1bd41930d78af7f51366b79a732fef93c0a/aerospike-client-c.ini#L2 is still on `4.6.1` but on Dockerfile, it has `4.6.3` as C_VERSION

**Comment by helipilot50** [comment]
Same issue

**Comment by jhecking** [comment]
Hey @helipilot50, there’s already a PR #333 open to update the Dockerfile for Alpine Linux. Can you try out [that version from the `docker-alpine-3-11` branch](https://github.com/aerospike/aerospike-client-nodejs/blob/1de66c55da8c29a76403a53f4b2ebdf1cb053026/docker/Dockerfile.alpine) and see if it works for you?

**Comment by pnutmath** [comment]
Following configuration I have used with latest `Dockerfile.aplpine` in this project

ENV AS_C_VERSION 4.6.16
ENV AS_NODEJS_VERSION 3.16.1


I am getting following errors:

```
Aug 18 2020 15:51:46 UTC: WARN (1) [as_pipe.c:208] [read_file] - Failed to open /proc/sys/net/core/wmem_max for reading
Aug 18 2020 15:51:46 UTC: WARN (1) [as_pipe.c:267] [get_buffer_size] - Failed to read /proc/sys/net/core/wmem_max; should be at least 5242880. Please verify.
Aug 18 2020 15:51:46 UTC: WARN (1) [as_pipe.c:208] [read_file] - Failed to open /proc/sys/net/core/rmem_max for reading
Aug 18 2020 15:51:46 UTC: WARN (1) [as_pipe.c:267] [get_buffer_size] - Failed to read /proc/sys/net/core/rmem_max; should be at least 15728640. Please verify.
```

**Comment by jhecking** [comment]
These are not errors but warnings that can be ignored. During startup, the client tries to check the OS network send/receive buffer sizes using the `net.core.wmem_max`/`net.core.rmem_max` system interfaces, which doesn't work inside a Docker container. So the client falls back to using reasonable default values.
