### ISSUE TITLE
 Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9'

### ISSUE THREAD

**Issue by Vidz51** [aerospike/aerospike-client-nodejs#369]
I am using aerospike in my node application. For deployment in centos 7 machine, using openssl 1.1.1. I am getting following error:

2020-06-02 16:00:35: Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/service/node_modules/aerospike/build/Release/aerospike.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.<anonymous> (/opt/service/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:172:43)
    at Function._load (/opt/service/node_modules/@sentry/node/dist/integrations/console.js:41:47)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/opt/service/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/service/node_modules/aerospike/lib/aerospike.js:19:31)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)

Kindly suggest a solution

**Comment by jhecking** [comment]
Was that binary `/opt/service/node_modules/aerospike/build/Release/aerospike.node` build on the same system where you are trying to run it? You mentioned in the other openssl issue you filed, that you are running this in Docker. What are you running as the host system and what's the base image of your Docker container?

**Comment by rake7h** [comment]
Hi @jhecking 

I'm getting same error on server start:

```
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/userxyz/app/node_modules/aerospike/build/Release/aerospike.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module.Hook._require.Module.require (/usr/local/userxyz/app/node_modules/require-in-the-middle/index.js:80:39)
```

This is happening when my app image is build on CI(jenkins) env and after that I run the same image on host env.

CI base image is **ubuntu**

app docker base image is **centos:7**

complete dockerfile of app:

```
FROM centos:7

ENV BUILD_ENV="staging"

RUN yum install -y wget epel-release gcc-c++ python-setuptools && \
  curl -fsSL https://rpm.nodesource.com/setup_12.x | bash - && \
  yum install -y nodejs && \
  yum install -y openssl-devel zlib-devel

RUN yum install -y nginx supervisor && \
  rm -f /etc/localtime && \
  ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && \
  mkdir -p /var/log/supervisor

## Copy all env config files
COPY dockerconfig/${BUILD_ENV}/nginx.conf /etc/nginx/nginx.conf
COPY dockerconfig/${BUILD_ENV}/supervisord.conf /etc/supervisord.conf
COPY dockerconfig/${BUILD_ENV}/appnginx.conf /etc/nginx/conf.d/default.conf
COPY dockerconfig/${BUILD_ENV}/services/* /etc/supervisord.d/
COPY dockerconfig/${BUILD_ENV}/supervisord /etc/rc.d/init.d
COPY entrypoint.sh /

RUN mkdir -p /usr/local/useretc/app
RUN mkdir -p /usr/local/useretc/app/logs
RUN mkdir -p /etc/supervisord.d

RUN chmod +x /entrypoint.sh
RUN chmod 755 /etc/rc.d/init.d/supervisord

WORKDIR /usr/local/useretc/app
EXPOSE 80

## Copy all require files for runtime
COPY ./ /usr/local/useretc/app/

# RUN npm install
RUN npm install
RUN npm run build

ENTRYPOINT ["/entrypoint.sh"]

CMD ["/usr/bin/supervisord", "-n"]
```

**Comment by jhecking** [comment]
Closing this as per https://github.com/aerospike/aerospike-client-nodejs/issues/442#issuecomment-996451605.
