### ISSUE TITLE
Build fails at query.cc

### ISSUE THREAD

**Issue by xorgy** [aerospike/aerospike-client-nodejs#37]
Build fails at query.cc.

CC is gcc 4.9.2, I tried with clang, but your build scripts rely on GCC-only flags (-fno-tree-vrp).

```
> aerospike@1.0.27 install /home/aaron/src/aerospike-node-demo/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/home/aaron/src/aerospike-node-demo/node_modules/aerospike/build'
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh aerospike-client-c/lib/libaerospike.a

CHECK
   [✓] /usr/lib/libaerospike.a
   [✓] /usr/include/aerospike/aerospike.h
   [✓] /usr/share/udf/lua/aerospike.lua

  TOUCH Release/obj.target/aerospike-client-c.stamp
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
  CXX(target) Release/obj.target/aerospike/src/main/client.o
  CXX(target) Release/obj.target/aerospike/src/main/client/batch_exists.o
  CXX(target) Release/obj.target/aerospike/src/main/client/batch_get.o
  CXX(target) Release/obj.target/aerospike/src/main/client/close.o
  CXX(target) Release/obj.target/aerospike/src/main/client/connect.o
  CXX(target) Release/obj.target/aerospike/src/main/client/execute.o
  CXX(target) Release/obj.target/aerospike/src/main/client/exists.o
  CXX(target) Release/obj.target/aerospike/src/main/client/get.o
  CXX(target) Release/obj.target/aerospike/src/main/client/info.o
  CXX(target) Release/obj.target/aerospike/src/main/client/operate.o
  CXX(target) Release/obj.target/aerospike/src/main/client/put.o
  CXX(target) Release/obj.target/aerospike/src/main/client/query.o
../src/main/client/query.cc: In static member function ‘static v8::Handle<v8::Value> AerospikeQuery::where(const v8::Arguments&)’:
../src/main/client/query.cc:222:10: error: ‘AS_PREDICATE_INTEGER_RANGE’ was not declared in this scope
     case AS_PREDICATE_INTEGER_RANGE:
          ^
../src/main/client/query.cc:230:10: error: ‘AS_PREDICATE_INTEGER_EQUAL’ was not declared in this scope
     case AS_PREDICATE_INTEGER_EQUAL:
          ^
../src/main/client/query.cc:238:10: error: ‘AS_PREDICATE_STRING_EQUAL’ was not declared in this scope
     case AS_PREDICATE_STRING_EQUAL:
          ^
../src/main/client/query.cc:242:59: error: ‘string_equals’ was not declared in this scope
      as_query_where( query, bin_name,string_equals(bin_val));
                                                           ^
aerospike.target.mk:131: recipe for target 'Release/obj.target/aerospike/src/main/client/query.o' failed
make: *** [Release/obj.target/aerospike/src/main/client/query.o] Error 1
make: Leaving directory '/home/aaron/src/aerospike-node-demo/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.18.4-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aaron/src/aerospike-node-demo/node_modules/aerospike
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.18.4-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "aerospike" "--python=python2"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE

npm ERR! aerospike@1.0.27 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerospike@1.0.27 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/aaron/src/aerospike-node-demo/npm-debug.log

```

**Comment by GayathriKaliyamoorthy** [comment]
Hi Xorgy,

Currently Aerospike Nodejs Client is dependent on a specific version of Aerospike C Client. This change is introduced from version 1.0.27. The current version of nodejs client(version 1.0.27) is dependent on 3.0.94 version of C client. You seem to have installed the latest version (3.0.96) version in your machine and trying to install nodejs on top that. The solution is to uninstall C client installed in your machine and do a simple `npm install aerospike`. That would resolve the dependency automatically and download the correct version of C client. 

Please uninstall the C client (3.0.96) and try installing nodejs client.

Thanks
Gayathri.K

**Comment by xorgy** [comment]
I see, I was under the impression that 3.0.96 was a normal patch release in the 3.0.x series, and that there would be no such regressions. What's the timeline for it being updated to support the more recent client?

**Comment by ryanwitt** [comment]
aerospike-client-nodejs@1.0.28 (on npm as of last night) downloads aerospike-c-client@3.0.96 by default now

**Comment by GayathriKaliyamoorthy** [comment]
@xorgy We have made an official release updating nodejs client to use the latest C client, version 3.0.96 yesterday. 

Thanks

**Comment by xorgy** [comment]
Sweet, it works now. I can't wait for stable releases of the c client.
