### ISSUE TITLE
Failed to install aerospike using npm on Ubuntu

### ISSUE THREAD

**Issue by pnutmath** [aerospike/aerospike-client-nodejs#380]
Command run: `npm i aerospike`
Node version: v12.18.3
npm version: 6.14.7
OS: Ubuntu 20.04

**Installation logs:**
 ```
npm install aerospike

> aerospike@3.16.1 install /home/abhay/Desktop/projects/<project>/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/home/abhay/Desktop/projects/<project>/node_modules/aerospike/build'
  TOUCH ebf8c619d512e7a1a724a0ecb06ec5eec50df7dc.intermediate
  ACTION binding_gyp_aerospike_client_c_target_Installing_Aerospike_C_Client_dependency ebf8c619d512e7a1a724a0ecb06ec5eec50df7dc.intermediate
info: downloading 'https://artifacts.aerospike.com/aerospike-client-c/4.6.16/aerospike-client-c-libuv-4.6.16.ubuntu18.04.x86_64.tgz' to 'aerospike-client-c-libuv-4.6.16.ubuntu18.04.x86_64.tgz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2341k  100 2341k    0     0  1831k      0  0:00:01  0:00:01 --:--:-- 1831k
grep aerospike-client-c-libuv-4.6.16.ubuntu18.04.x86_64.tgz /home/abhay/Desktop/projects/<project>/node_modules/aerospike/aerospike-client-c.sha256
info: verifying checksum for 'aerospike-client-c-libuv-4.6.16.ubuntu18.04.x86_64.tgz': OK
info: extracting devel package from 'aerospike-client-c-libuv-4.6.16.ubuntu18.04.x86_64.tgz'
info: extracting files from 'aerospike-client-c-libuv-devel-4.6.16.ubuntu18.04.x86_64.deb'

CHECK
   [✓] /home/abhay/Desktop/projects/<project>/node_modules/aerospike/aerospike-client-c/package/usr/lib/libaerospike.a
   [✓] /home/abhay/Desktop/projects/<project>/node_modules/aerospike/aerospike-client-c/package/usr/include/aerospike/aerospike.h

  TOUCH Release/obj.target/aerospike-client-c.stamp
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
  CXX(target) Release/obj.target/aerospike/src/main/client.o
  CXX(target) Release/obj.target/aerospike/src/main/config.o
  CXX(target) Release/obj.target/aerospike/src/main/events.o
  CXX(target) Release/obj.target/aerospike/src/main/cdt_ctx.o
  CXX(target) Release/obj.target/aerospike/src/main/operations.o
  CXX(target) Release/obj.target/aerospike/src/main/scalar_operations.o
  CXX(target) Release/obj.target/aerospike/src/main/list_operations.o
  CXX(target) Release/obj.target/aerospike/src/main/map_operations.o
  CXX(target) Release/obj.target/aerospike/src/main/bit_operations.o
  CXX(target) Release/obj.target/aerospike/src/main/hll_operations.o
  CXX(target) Release/obj.target/aerospike/src/main/policy.o
  CXX(target) Release/obj.target/aerospike/src/main/query.o
  CXX(target) Release/obj.target/aerospike/src/main/scan.o
  CXX(target) Release/obj.target/aerospike/src/main/predexp.o
  CXX(target) Release/obj.target/aerospike/src/main/async.o
  CXX(target) Release/obj.target/aerospike/src/main/command.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/apply_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/batch_exists.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/batch_get.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/batch_select.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/batch_read_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/exists_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/get_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/info_any.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/info_foreach.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/info_host.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/info_node.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/job_info.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/operate_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/put_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/query_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/query_apply.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/query_background.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/query_foreach.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/remove_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/scan_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/scan_background.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/select_async.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/truncate.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/index_create.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/index_remove.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/udf_register.o
  CXX(target) Release/obj.target/aerospike/src/main/commands/udf_remove.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/predicates.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/bitwise_enum.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/hll_enum.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/maps.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/lists.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/index.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/policy_enum.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/status.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/scanPriority.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/job_status.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/udf_languages.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/ttl.o
  CXX(target) Release/obj.target/aerospike/src/main/enums/config_enum.o
  CXX(target) Release/obj.target/aerospike/src/main/stats.o
  CXX(target) Release/obj.target/aerospike/src/main/util/conversions.o
  CXX(target) Release/obj.target/aerospike/src/main/util/log.o
  SOLINK_MODULE(target) Release/obj.target/aerospike.node
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lssl
collect2: error: ld returned 1 exit status
make: *** [aerospike.target.mk:219: Release/obj.target/aerospike.node] Error 1
rm ebf8c619d512e7a1a724a0ecb06ec5eec50df7dc.intermediate
make: Leaving directory '/home/abhay/Desktop/projects/<project>/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/abhay/Desktop/projects/<project>/node_modules/aerospike
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aerospike@3.16.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerospike@3.16.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abhay/.npm/_logs/2020-08-17T15_38_35_228Z-debug.log
```

**Comment by pnutmath** [comment]
Works after required dependency installation:

`sudo apt-get install g++ libssl1.0.0 libssl-dev zlib1g-dev`

cant we check and install required dependecies with npm?

**Comment by jhecking** [comment]
The system dependencies are detailed here: https://github.com/aerospike/aerospike-client-nodejs#Prerequisites. Typically npm packages don't install system dependencies as those dependencies would vary from system to system.
