### ISSUE TITLE
Benchmark file in Nodejs gives out error

### ISSUE THREAD

**Issue by adityarar** [aerospike/aerospike-client-nodejs#407]
I am trying to run benchmark file benchmarks/main.js

**Steps**:
Git clone
npm install
npm update
node benchmarks/main.js

Following error comes up:

```
TypeError: winston.Logger is not a constructor
/.../aerospike-client-nodejs/benchmarks/main.js:89
var logger = new (winston.Logger)({
             ^

TypeError: winston.Logger is not a constructor
    at Object.<anonymous> (/.../aerospike-client-nodejs/benchmarks/main.js:89:14)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```

On searching around I found that this is happening due to lower version of winston being used.

Shouldn't this be fixed in the repo?

Node version: 12.3.1

**Comment by jhecking** [comment]
Thanks for reporting this. Yes, of course this should be fixed in the repo!
