### ISSUE TITLE
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by rake7h** [aerospike/aerospike-client-nodejs#442]
I'm getting error on server start:

```
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/userxyz/app/node_modules/aerospike/build/Release/aerospike.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module.Hook._require.Module.require (/usr/local/userxyz/app/node_modules/require-in-the-middle/index.js:80:39)
```
version:
"aerospike": "^3.16.6",

This is happening when my app image is build on CI(jenkins) env and after that I run the same image on host env.

CI platform is **ubuntu**

app docker base image is **centos:7**

complete dockerfile of app:

```
FROM centos:7

ENV BUILD_ENV="staging"

RUN yum install -y wget epel-release gcc-c++ python-setuptools && \
  curl -fsSL https://rpm.nodesource.com/setup_12.x | bash - && \
  yum install -y nodejs && \
  yum install -y openssl-devel zlib-devel

RUN yum install -y nginx supervisor && \
  rm -f /etc/localtime && \
  ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && \
  mkdir -p /var/log/supervisor

## Copy all env config files
COPY dockerconfig/${BUILD_ENV}/nginx.conf /etc/nginx/nginx.conf
COPY dockerconfig/${BUILD_ENV}/supervisord.conf /etc/supervisord.conf
COPY dockerconfig/${BUILD_ENV}/appnginx.conf /etc/nginx/conf.d/default.conf
COPY dockerconfig/${BUILD_ENV}/services/* /etc/supervisord.d/
COPY dockerconfig/${BUILD_ENV}/supervisord /etc/rc.d/init.d
COPY entrypoint.sh /

RUN mkdir -p /usr/local/useretc/app
RUN mkdir -p /usr/local/useretc/app/logs
RUN mkdir -p /etc/supervisord.d

RUN chmod +x /entrypoint.sh
RUN chmod 755 /etc/rc.d/init.d/supervisord

WORKDIR /usr/local/useretc/app
EXPOSE 80

## Copy all require files for runtime
COPY ./ /usr/local/useretc/app/

# RUN npm install
RUN npm install
RUN npm run build

ENTRYPOINT ["/entrypoint.sh"]

CMD ["/usr/bin/supervisord", "-n"]
```
 
 NOTE: This is working without any error when i build and run image on same machine. It's working on my local docker desktop on mac.

**Comment by rake7h** [comment]
update: this got fixed with centos:8 base image.
