### ISSUE TITLE
Can not install on io.js 1.8.1

### ISSUE THREAD

**Issue by miktam** [aerospike/aerospike-client-nodejs#51]
It seems that compiler in io.js is more strict that in node 0.12:

```
...
CXX(target) Release/obj.target/aerospike/src/main/util/log.o
../src/main/util/log.cc:135:27: error: comparison between pointer and integer ('const char *' and 'int')
        if ( err->message != '\0') {
             ~~~~~~~~~~~~ ^  ~~~~
```

Current line generates just a warning in node 0.12.2

**Comment by cstivers78** [comment]
We made the fix internally, the change will go out with the next release.

**Comment by GayathriKaliyamoorthy** [comment]
Hi,

We made a release to NPM repository with the fix. The fix is available in the version 1.0.38

**Comment by woozyking** [comment]
This breaks the installation on Node 0.12.2

```
> aerospike@1.0.38 install /home/deploy/deploy/node_modules/aerospike
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:40:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:43:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:54:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/deploy/deploy/node_modules/aerospike
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! aerospike@1.0.38 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerospike@1.0.38 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
```

**Comment by miktam** [comment]
@GayathriKaliyamoorthy it works with the newest iojs, thank you
