### ISSUE TITLE
Issue with using client.operate with policy exists: AS.policy.exists.CREATE

### ISSUE THREAD

**Issue by Nazar910** [aerospike/aerospike-client-nodejs#565]
Client version: 5.4.0
Server version: 6.0.0.3
OS: macOS, Ubuntu
Arch: arm (Apple M1 Pro), x86_64

Hi, I'm having problems with using `client.operate` for creating new record if it isn't created yet (using `exists` flag from doc https://docs.aerospike.com/apidocs/nodejs/operatepolicy#exists__anchor). But for some reason I keep getting errors `Record does not exists` instead of having it created for me.
I really appreciate any help here (maybe I'm using it incorrectly or smth). Thanks in advance!

Code sample: 
```javascript
const AS = require('aerospike');

async function main() {
    const cli = await AS.connect({
        hosts: '127.0.0.1'
    });

    const key = new AS.Key('cdp', 'test', 'key123');
    const ops = [
        AS.lists.append('foo', '2', new AS.ListPolicy({ writeFlags: AS.lists.writeFlags.ADD_UNIQUE | AS.lists.writeFlags.NO_FAIL })),
        AS.operations.touch(86400),
    ];
    await cli.operate(key, ops, {}, { exists: AS.policy.exists.CREATE });

    console.log('record after', await cli.get(key));
}

if (require.main === module) {
    main();
}
```

Error 
```
AerospikeError: [::1]:3000 Record does not exist in database. May be returned by read, or write with policy Aerospike.policy.exists.UPDATE
    at Function.fromASError (/Users/salamander/playground/as/node_modules/aerospike/lib/error.js:118:21)
    at OperateCommand.convertError (/Users/salamander/playground/as/node_modules/aerospike/lib/commands/command.js:89:27)
    at OperateCommand.convertResponse (/Users/salamander/playground/as/node_modules/aerospike/lib/commands/command.js:99:24)
    at asCallback (/Users/salamander/playground/as/node_modules/aerospike/lib/commands/command.js:161:24) {
  code: 2,
  command: OperateCommand {
    client: Client {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      config: Config {
        clusterName: undefined,
        port: 3000,
        hosts: 'localhost:3000',
        policies: {},
        useAlternateAccessAddress: false,
        rackAware: undefined
      },
      as_client: AerospikeClient {},
      connected: true,
      captureStackTraces: false,
      [Symbol(kCapture)]: false
    },
    args: [
      Key {
        ns: 'cdp',
        set: 'test',
        key: 'key123',
        digest: Buffer(20) [Uint8Array] [
           23, 226,  78, 251,  35, 106,
          208, 195, 230, 167, 254, 136,
          245,  66,  63, 237, 153, 150,
          213,  68
        ]
      },
      [
        ListOperation {
          op: 258,
          bin: 'foo',
          value: '2',
          policy: ListPolicy { order: undefined, writeFlags: 5 }
        },
        Operation { op: 5, bin: undefined, ttl: 86400 }
      ],
      {},
      { exists: 1 }
    ],
    captureStackTraces: false,
    key: Key {
      ns: 'cdp',
      set: 'test',
      key: 'key123',
      digest: Buffer(20) [Uint8Array] [
         23, 226,  78, 251,  35, 106,
        208, 195, 230, 167, 254, 136,
        245,  66,  63, 237, 153, 150,
        213,  68
      ]
    },
    ensureConnected: true
  },
  func: 'as_event_command_parse_result',
  file: 'src/main/aerospike/as_event.c',
  line: 1356,
  inDoubt: false
}
```

**Comment by DomPeliniAerospike** [comment]
Hi @Nazar910,
Sorry for the late response. You need to put a record before you can append a record. To my knowledge, you cannot append to a  bin for a record that does not exist.  Simply use a put to place the record before the operation.
`
const AS = require('aerospike');
async function main() {
    const cli = await AS.connect({
        hosts: '172.17.0.2'
    });

    const key = new AS.Key('test', 'demo', 'key123');
    cli.put(key, {"claw": 5})
    const ops = [
        AS.lists.append('foo', '5', new AS.ListPolicy({ writeFlags: AS.lists.writeFlags.ADD_UNIQUE | AS.lists.writeFlags.NO_FAIL })),
        AS.operations.touch(86400),
    ];
    await cli.operate(key, ops, {}, { exists: AS.policy.exists.UPDATE });

    console.log('record after', await cli.get(key));
    cli.remove(key)
    cli.close()
}

if (require.main === module) {
    main();
}`

Sorry for the poor formatting. I will try to have a faster response time in the future.  Please feel free to reopen this issue if you have more questions.
