### ISSUE TITLE
installation fails on various distros (Centos7, U15)

### ISSUE THREAD

**Issue by blitzprog** [aerospike/aerospike-client-nodejs#57]
```
eduard@home:~$ npm install aerospike
/
> aerospike@1.0.39 install /home/eduard/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/home/eduard/node_modules/aerospike/build'
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh aerospike-client-c/lib/libaerospike.a
error: ubuntu15 is not supported.
aerospike-client-c.target.mk:13: recipe for target 'aerospike-client-c/lib/libaerospike.a' failed
make: *** [aerospike-client-c/lib/libaerospike.a] Error 1
make: Leaving directory '/home/eduard/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/eduard/.nvm/versions/io.js/v2.0.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Linux 3.19.0-17-generic
gyp ERR! command "/home/eduard/.nvm/versions/io.js/v2.0.2/bin/iojs" "/home/eduard/.nvm/versions/io.js/v2.0.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/eduard/node_modules/aerospike
gyp ERR! node -v v2.0.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.19.0-17-generic
npm ERR! argv "/home/eduard/.nvm/versions/io.js/v2.0.2/bin/iojs" "/home/eduard/.nvm/versions/io.js/v2.0.2/bin/npm" "install" "aerospike"
npm ERR! node v2.0.2
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! aerospike@1.0.39 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerospike@1.0.39 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eduard/npm-debug.log
```

https://github.com/nodejs/io.js/issues/1620

**Comment by blitzprog** [comment]
This seems to be ubuntu15 if I interpret this correctly? I can't even install Aerospike on the official **node 0.12.3**:
```
eduard@home:~/test$ npm install aerospike
|
> aerospike@1.0.39 install /home/eduard/test/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/home/eduard/test/node_modules/aerospike/build'
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh aerospike-client-c/lib/libaerospike.a
error: ubuntu15 is not supported.
aerospike-client-c.target.mk:13: recipe for target 'aerospike-client-c/lib/libaerospike.a' failed
make: *** [aerospike-client-c/lib/libaerospike.a] Error 1
make: Leaving directory '/home/eduard/test/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/eduard/.nvm/versions/node/v0.12.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.0-17-generic
gyp ERR! command "node" "/home/eduard/.nvm/versions/node/v0.12.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/eduard/test/node_modules/aerospike
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.19.0-17-generic
npm ERR! argv "/home/eduard/.nvm/versions/node/v0.12.3/bin/node" "/home/eduard/.nvm/versions/node/v0.12.3/bin/npm" "install" "aerospike"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! aerospike@1.0.39 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerospike@1.0.39 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eduard/test/npm-debug.log
```

**Comment by GayathriKaliyamoorthy** [comment]
Hi @blitzprog 
Yes, it's related to Ubuntu 15. We do not yet officially support it on Ubuntu15. Will update you once we start supporting for Ubuntu 15.

Thanks

**Comment by blitzprog** [comment]
@GayathriKaliyamoorthy Thanks for the quick reply! Will happily wait for it.

**Comment by DamilolaJegede** [comment]
It's not only Ubuntu. We're seeing the same thing on our new Centos 7 box:

```
root@box ~]# npm install aerospike
npm http GET https://registry.npmjs.org/aerospike
npm http 304 https://registry.npmjs.org/aerospike
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> aerospike@1.0.39 install /root/node_modules/aerospike
> node-gyp rebuild

make: Entering directory `/root/node_modules/aerospike/build'
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh aerospike-client-c/lib/libaerospike.a
which: no lsb_release in (/usr/lib/node_modules/npm/bin/node-gyp-bin:/root/node_modules/aerospike/node_modules/.bin:/root/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
error:  is not supported.
make: *** [aerospike-client-c/lib/libaerospike.a] Error 1
make: Leaving directory `/root/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.10.0-123.8.1.el7.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/aerospike
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by bbulkow** [comment]
This problem is not limited to node 0.12, it happens with node 0.10 on centos 7.

As another datapoint, I installed node / npm on Centos7 the following way (fresh Centos VM)
sudo yum install epel-release
sudo yum update
sudo yum install nodejs npm
# node version is currently 0.10.36 - this was about 120 packages including g++
npm install aerospike

And I also got....
> aerospike@1.0.39 install /home/brian/node_modules/aerospike
> node-gyp rebuild

make: Entering directory `/home/brian/node_modules/aerospike/build'
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh aerospike-client-c/lib/libaerospike.a
which: no lsb_release in (/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/brian/node_modules/aerospike/node_modules/.bin:/home/brian/node_modules/.bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/brian/.local/bin:/home/brian/bin)
error:  is not supported.

**Comment by GayathriKaliyamoorthy** [comment]
I have added support for centos 7 and ubuntu15 and the QA is also done. We will make an official release by tomorrow(25th May). Thanks for your patience.

Thanks
Gayathri

**Comment by blitzprog** [comment]
Looking forward to trying it, awesome news!

**Comment by blitzprog** [comment]
Was there a problem with the new release? Seems to be at [1.0.39](https://www.npmjs.com/package/aerospike) still.

**Comment by GayathriKaliyamoorthy** [comment]
Hi 
We made a release two days. Could you please give us your feedback, so that we can close this case.

Thanks

**Comment by blitzprog** [comment]
```
> aerospike@1.0.40 install /home/eduard/projects/aero/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/home/eduard/projects/aero/node_modules/aerospike/build'
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh aerospike-client-c/lib/libaerospike.a
info: downloading 'http://www.aerospike.com/download/client/c/3.1.8/artifact/ubuntu12' to '/home/eduard/projects/aero/node_modules/aerospike/aerospike-client-c/package/aerospike-client-c.tgz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   350  100   350    0     0   1001      0 --:--:-- --:--:-- --:--:--  1000
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 15.2M  100 15.2M    0     0  2455k      0  0:00:06  0:00:06 --:--:-- 3415k
info: extracting 'aerospike-client-c-3.1.8.ubuntu12.04.x86_64/aerospike-client-c-devel-3.1.8.ubuntu12.04.x86_64.deb' from 'aerospike-client-c.tgz'
info: extracting files from 'aerospike-client-c-3.1.8.ubuntu12.04.x86_64/aerospike-client-c-devel-3.1.8.ubuntu12.04.x86_64.deb'

CHECK
   [✓] /home/eduard/projects/aero/node_modules/aerospike/aerospike-client-c/package/usr/lib/libaerospike.a
   [✓] /home/eduard/projects/aero/node_modules/aerospike/aerospike-client-c/package/usr/include/aerospike/aerospike.h
   [✓] /home/eduard/projects/aero/node_modules/aerospike/aerospike-client-c/package/opt/aerospike/client/sys/udf/lua/aerospike.lua

  TOUCH Release/obj.target/aerospike-client-c.stamp
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
In file included from ../node_modules/nan/nan_new.h:181:0,
                 from ../node_modules/nan/nan.h:74,
                 from ../src/main/aerospike.cc:18:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../node_modules/nan/nan_implementation_12_inl.h:172:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:172:76: note: candidate is:
In file included from /home/eduard/.node-gyp/2.1.0/src/node.h:42:0,
                 from ../src/main/aerospike.cc:17:
/home/eduard/.node-gyp/2.1.0/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/eduard/.node-gyp/2.1.0/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
aerospike.target.mk:137: recipe for target 'Release/obj.target/aerospike/src/main/aerospike.o' failed
make: *** [Release/obj.target/aerospike/src/main/aerospike.o] Error 1
make: Leaving directory '/home/eduard/projects/aero/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/eduard/.nvm/versions/io.js/v2.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Linux 3.19.0-17-generic
gyp ERR! command "/home/eduard/.nvm/versions/io.js/v2.1.0/bin/iojs" "/home/eduard/.nvm/versions/io.js/v2.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/eduard/projects/aero/node_modules/aerospike
gyp ERR! node -v v2.1.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.19.0-17-generic
npm ERR! argv "/home/eduard/.nvm/versions/io.js/v2.1.0/bin/iojs" "/home/eduard/.nvm/versions/io.js/v2.1.0/bin/npm" "install" "aerospike"
npm ERR! node v2.1.0
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! aerospike@1.0.40 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerospike@1.0.40 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eduard/projects/aero/npm-debug.log
```

io.js 2.1.0 fails. [See my benchmarks](https://github.com/blitzprog/webserver-benchmarks) why io.js support would be interesting for aerospike as a performance-oriented database.

node.js 0.12.4 **works** (great!) but it feels counter-intuitive to switch to node for lower performance just to be able to use Aerospike. On my [own web server](https://github.com/freezingwind/aero) I noticed around ~15-20% slowdown when switching to node.

In the future we should be seeing those projects slowly merging together but "future" is anything but a clearly set date.

In the meantime, if you decide that io.js is too difficult to support, I have of course no option but to respect that decision but the 20% performance loss makes it *not* worth downgrading for me just to be able to support AS. This is just my perspective.

**Comment by bbulkow** [comment]
The distro issue with U15.05 and Centos 7 seems resolved, no ?

This appears to be a report for io.js not being supported, which was never claimed.

Regarding io.js, we are happy to support someone who would like to port this driver to that fork. io.js will be a better platform with support for Aerospike. If, as Schuleter believes, the io.js fork will merge with the node.js fork, then we can simply support one.

**Comment by blitzprog** [comment]
Aye, this can be closed. I'm hoping for the best, too.

**Comment by rahulbhanushali** [comment]
**io.js has merged with the Node.js project again.**
_There won't be any further io.js releases. All of the features in io.js are available in Node.js v4 and above._ - https://iojs.org/en/

So is it safe for us to assume that aerospike client will work on CentOS7? 
The readme file does not mention anything about CentOS7.

**Comment by jhecking** [comment]
@rahulbhanushali, I have just updated the readme to indicate that CentOS 7/RHEL 7 are supported as well.

I'm not sure what the reference to io.js has to do with this though?

**Comment by rahulbhanushali** [comment]
@jhecking, you're right, this has nothing to do with io.js. Just wanted to make sure since io and node have merged than this should be a problem anymore.

Thank you for confirming and updating the docs.
