### ISSUE TITLE
installation fails on debian8 "jessie"

### ISSUE THREAD

**Issue by IncSW** [aerospike/aerospike-client-nodejs#72]
```
/home/tmp # npm install aerospike
/
> aerospike@1.0.45 install /home/tmp/node_modules/aerospike
> node-gyp rebuild

make: Entering directory '/home/tmp/node_modules/aerospike/build'
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh aerospike-client-c/lib/libaerospike.a
info: downloading 'http://www.aerospike.com/download/client/c/3.1.16/artifact/debian8' to '/home/tmp/node_modules/aerospike/aerospike-client-c/package/aerospike-client-c.tgz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   350  100   350    0     0    940      0 --:--:-- --:--:-- --:--:--   938
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
info: extracting '' from 'aerospike-client-c.tgz'

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
info: extracting files from ''
dpkg-deb: error: failed to read archive `aerospike-client-c-devel-*.deb': No such file or directory

CHECK
   [â] /home/tmp/node_modules/aerospike/aerospike-client-c/package/usr/lib/libaerospike.a
   [â] /home/tmp/node_modules/aerospike/aerospike-client-c/package/usr/include/aerospike/aerospike.h
   [â] /home/tmp/node_modules/aerospike/aerospike-client-c/package/opt/aerospike/client/sys/udf/lua/aerospike.lua

aerospike-client-c.target.mk:13: recipe for target 'aerospike-client-c/lib/libaerospike.a' failed
make: *** [aerospike-client-c/lib/libaerospike.a] Error 1
make: Leaving directory '/home/tmp/node_modules/aerospike/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tmp/node_modules/aerospike
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "aerospike"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! aerospike@1.0.45 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aerospike@1.0.45 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tmp/npm-debug.log
```
In https://github.com/aerospike/aerospike-client-nodejs/blob/master/scripts/aerospike-client-c.sh
```
detect_linux()
{
***
      "debian6" | "debian7" | "debian8" )
        echo ${DIST_NAME} "deb"
        return 0
        ;;
***
}
```
It generates http://www.aerospike.com/download/client/c/3.1.16/artifact/debian8
This link returns 404 error.

**Comment by GayathriKaliyamoorthy** [comment]
The fix is available from release [1.0.49](https://github.com/aerospike/aerospike-client-nodejs/releases/tag/1.0.49)
