### ISSUE TITLE
Module does not compile with node 4.0

### ISSUE THREAD

**Issue by revington** [aerospike/aerospike-client-nodejs#90]
```

> aerospike@1.0.50 install /home/pedro/Documents/work/d3media/user-matching/node_modules/aerospike
> node-gyp rebuild

make: Entering directory `/home/pedro/Documents/work/d3media/user-matching/node_modules/aerospike/build'
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh aerospike-client-c/lib/libaerospike.a
info: downloading 'http://www.aerospike.com/download/client/c/3.1.16/artifact/ubuntu12' to '/home/pedro/Documents/work/d3media/user-matching/node_modules/aerospike/aerospike-client-c/package/aerospike-client-c.tgz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   351  100   351    0     0    945      0 --:--:-- --:--:-- --:--:--   943

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0 15.3M    0 73548    0     0  59792      0  0:04:29  0:00:01  0:04:28 59792
 12 15.3M   12 1887k    0     0   837k      0  0:00:18  0:00:02  0:00:16 1774k
 37 15.3M   37 5930k    0     0  1638k      0  0:00:09  0:00:03  0:00:06 2453k
 43 15.3M   43 6811k    0     0  1583k      0  0:00:09  0:00:04  0:00:05 2195k
 44 15.3M   44 6988k    0     0  1345k      0  0:00:11  0:00:05  0:00:06 1744k
 53 15.3M   53 8358k    0     0  1352k      0  0:00:11  0:00:06  0:00:05 1674k
 78 15.3M   78 11.9M    0     0  1708k      0  0:00:09  0:00:07  0:00:02 2106k
 88 15.3M   88 13.5M    0     0  1691k      0  0:00:09  0:00:08  0:00:01 1733k
 89 15.3M   89 13.7M    0     0  1518k      0  0:00:10  0:00:09  0:00:01 1462k
 99 15.3M   99 15.2M    0     0  1531k      0  0:00:10  0:00:10 --:--:-- 1726k
100 15.3M  100 15.3M    0     0  1530k      0  0:00:10  0:00:10 --:--:-- 1798k
info: extracting 'aerospike-client-c-3.1.16.ubuntu12.04.x86_64/aerospike-client-c-devel-3.1.16.ubuntu12.04.x86_64.deb' from 'aerospike-client-c.tgz'
info: extracting files from 'aerospike-client-c-3.1.16.ubuntu12.04.x86_64/aerospike-client-c-devel-3.1.16.ubuntu12.04.x86_64.deb'

CHECK
   [✓] /home/pedro/Documents/work/d3media/user-matching/node_modules/aerospike/aerospike-client-c/package/usr/lib/libaerospike.a
   [✓] /home/pedro/Documents/work/d3media/user-matching/node_modules/aerospike/aerospike-client-c/package/usr/include/aerospike/aerospike.h
   [✓] /home/pedro/Documents/work/d3media/user-matching/node_modules/aerospike/aerospike-client-c/package/opt/aerospike/client/sys/udf/lua/aerospike.lua

  TOUCH Release/obj.target/aerospike-client-c.stamp
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
In file included from ../src/main/aerospike.cc:18:0:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: error: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: error: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/main/aerospike.cc:18:
/home/pedro/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pedro/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/pedro/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pedro/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/main/aerospike.cc:18:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/aerospike/src/main/aerospike.o] Error 1
make: Leaving directory `/home/pedro/Documents/work/d3media/user-matching/node_modules/aerospike/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pedro/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-54-generic
gyp ERR! command "/home/pedro/.nvm/versions/node/v4.0.0/bin/node" "/home/pedro/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pedro/Documents/work/d3media/user-matching/node_modules/aerospike
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Linux 3.13.0-54-generic
npm ERR! argv "/home/pedro/.nvm/versions/node/v4.0.0/bin/node" "/home/pedro/.nvm/versions/node/v4.0.0/bin/npm" "i"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! aerospike@1.0.50 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerospike@1.0.50 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pedro/Documents/work/d3media/user-matching/npm-debug.log
```

**Comment by rbotzer** [comment]
Didn't node 4.0.0 _just_ come out? :wink:

**Comment by bbulkow** [comment]
IO.js 3.x was a virtual staging area for these changes, Aerospike was notified that this extension didn't compile with IO.js 3.x weeks (months?) ago.

**Comment by revington** [comment]
@rbotzer I have been waiting a looooooot! :)

**Comment by ngzhongcai** [comment]
Not just v4. Doesn't work for v0.10.36, and v0.12.7 as well

**Comment by bbulkow** [comment]
Compiles great for me with 0.12.7 - and others. Please post your 0.10 and 0.12 errors in a separate thread.

**Comment by rschmukler** [comment]
references #87 in terms of the `iojs@v3` stuff. Looks like the [NaN Module](https://www.npmjs.com/package/nan)

**Comment by bzkdjc** [comment]
:( 
Node v4 appears to be the best Node (_nodejs+iojs_)  till now and will go better as new versions get released. 
An even better version is under way and will be announced soon. 
So just a question: Why should we stay on deprecated versions to be able to use aerospike-nodejs?

**Comment by GayathriKaliyamoorthy** [comment]
We are working on supporting node.js 4.0. We have integrated with Nan module to maintain compatibility with all node versions. v0.10.x, v0.12.x, iojs and node4.0. For node.js4.0 to compile, Nan 2.x is required but Nan2.x is not backward compatible with Nan1.x. We are actively tracking the changes and working on upgrading Aerospike Driver to use Nan2.x. Sorry for the inconvenience. Expect a release soon.

Thanks.

**Comment by DamilolaJegede** [comment]
Thanks, guys! We're eagerly waiting.

**Comment by blitzprog** [comment]
Thanks for the news.

**Comment by NawarA** [comment]
@GayathriKaliyamoorthy Thanks for working on this. 

Can you give us an estimated time of release? This is a production level issue for us, and a bit of transparency would be very greatly appreciated.

Thank you again

**Comment by bbulkow** [comment]
NawarA, if you are an Aerospike Enterprise user, and you're using Aerospike in production with Node, please contact our support organization. If you have a production issue, call us IMMEDIATELY.

We don't release dates for our open source releases, but this is being actively worked on and we don't expect the delay to be long.

**Comment by NawarA** [comment]
We are an Enterprise user. Great will do. Looking forward to chatting

**Comment by bbulkow** [comment]
408-462-AERO , or support@aerospike.com . We never sleep .

**Comment by GayathriKaliyamoorthy** [comment]
Hi,

The latest release 1.0.51  supports node v4.x. Please upgrade to the latest and give your feedback.

Thanks

**Comment by plelevier** [comment]
After a few tests using node 4.1.1, it works for me.

For the record, if you use Travis-CI you'll certainly need to update the C++ environment to compile the aerospike client, since we now need a C++11 compiler : 

```yaml
sudo: false

language: node_js

node_js:
  - "4.1"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

[...]
```

I found this solution here : https://github.com/netiam/experiments/blob/b700b5176bd185a272c7c21c24bbc4fa6a3e36bd/.travis.yml
