### ISSUE TITLE
Version 1.0.51 doesn't build

### ISSUE THREAD

**Issue by Snesi** [aerospike/aerospike-client-nodejs#94]

**Comment by GayathriKaliyamoorthy** [comment]
Could you add the error messages when the build fails, along with node version and npm version, you are using?

Thanks

**Comment by Snesi** [comment]
Of course, sorry! 

* node `v0.10.36`
* npm `1.3.6`
Error message:
```
> aerospike@1.0.51 install /srv/moca/console/node_modules/aerospike
> node-gyp rebuild

make: se ingresa al directorio `/srv/moca/console/node_modules/aerospike/build'
  ACTION aerospike-client-c_run_scripts/aerospike-client-c.sh aerospike-client-c/lib/libaerospike.a
which: no lsb_release in (/usr/lib/node_modules/npm/bin/node-gyp-bin:/srv/moca/console/node_modules/aerospike/node_modules/.bin:/srv/moca/console/node_modules/.bin:/usr/bin:/sbin:/bin:/usr/sbin:/usr/bin)
info: downloading 'http://www.aerospike.com/download/client/c/3.1.22/artifact/el6' to '/srv/moca/console/node_modules/aerospike/aerospike-client-c/package/aerospike-client-c.tgz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   346  100   346    0     0   1061      0 --:--:-- --:--:-- --:--:--  1061
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 16.8M  100 16.8M    0     0  3155k      0  0:00:05  0:00:05 --:--:-- 4073k
info: extracting 'aerospike-client-c-3.1.22.el6.x86_64/aerospike-client-c-devel-3.1.22-1.el6.x86_64.rpm' from 'aerospike-client-c.tgz'
info: extracting files from 'aerospike-client-c-3.1.22.el6.x86_64/aerospike-client-c-devel-3.1.22-1.el6.x86_64.rpm'
13142 blocks

CHECK
   [✓] /srv/moca/console/node_modules/aerospike/aerospike-client-c/package/usr/lib/libaerospike.a
   [✓] /srv/moca/console/node_modules/aerospike/aerospike-client-c/package/usr/include/aerospike/aerospike.h
   [✓] /srv/moca/console/node_modules/aerospike/aerospike-client-c/package/opt/aerospike/client/sys/udf/lua/aerospike.lua

  TOUCH Release/obj.target/aerospike-client-c.stamp
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
In file included from ../src/include/client.h:20:0,
                 from ../src/main/aerospike.cc:17:
../node_modules/nan/nan.h:316:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
make: *** [Release/obj.target/aerospike/src/main/aerospike.o] Error 1
make: se sale del directorio `/srv/moca/console/node_modules/aerospike/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.14.48-33.39.amzn1.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/moca/console/node_modules/aerospike
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by GayathriKaliyamoorthy** [comment]
You are using a very old version of npm.  You can upgrade the npm version to the latest. That should solve this problem. For the reference see the discussion here [nan issue] (https://github.com/nodejs/nan/issues/414)

**Comment by Snesi** [comment]
Right! Installed npm (after breaking npm by doing `npm i -g npm`) and I don't get the error anymore!

Thank you! :smile:
