### ISSUE TITLE
Build Failed - Node V5

### ISSUE THREAD

**Issue by milonas115** [aerospike/aerospike-client-nodejs#97]
make: *** [Release/obj.target/aerospike/src/main/aerospike.o] Error 1
make: Leaving directory `/nodejs/node_modules/aerospike/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /nodejs/node_modules/aerospike
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN ENOENT ENOENT: no such file or directory, open '/nodejs/package.json'
npm WARN EPEERINVALID mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.
npm WARN EPACKAGEJSON nodejs No description
npm WARN EPACKAGEJSON nodejs No repository field.
npm WARN EPACKAGEJSON nodejs No README data
npm WARN EPACKAGEJSON nodejs No license field.
npm ERR! Linux 2.6.32-504.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "aerospike"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! aerospike@1.0.53 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aerospike@1.0.53 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /nodejs/npm-debug.log

**Comment by milonas115** [comment]
Fixed......Had to upgrade GCC to version 4.8.2 for it to install without issues. You should make a note of this in your docs somewhere as CentosOS 6.5/6.7 doesn't come by default with any repos supporting this version.
